name: Running Pillow
favicon: null
layout_spectrum: 0.49703
typography_spectrum: 0.42899
title: Running Pillow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c7c7c7'
    - '#2b2a29'
    - '#616161'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
